@startuml
skinparam ranksep 10
class AppService {
    - User user
    - searchProduct()
}

class User {
    - List<Strings> allergens
}
class Product {
}
class Dish {
    - Set<Product, weight> ingredients
}

package "util" {
    class DbConnector {
        - create()
        - read()
        - update()
        - delete()
        - saveProduct()
        - getProduct()
    }
    class ApiService {
        - searchProduct()
    }
    class TextUI {
        - TextUI()
        - Scanner scanner
        + void displayMsg(String s)
        + int promptNumeric(String msg)
        + String promptText(String msg)
        + int promptChoice(String msg, List<String> list)
        + boolean promptBinary(String msg )
        }
    class Authorization {
        - Login()
        - SignUp()
    }
}

AppService *-down- User
User *-down- Product
User *- Dish
Dish *- Product

@enduml