@startuml
skinparam ranksep 20
entity Users
entity Products
entity Dishes
entity UsersDishes
entity UsersProducts

Users ||--right--|{ UsersDishes
Users ||--down--|{ UsersProducts
UsersDishes }|--down--|| Dishes
UsersProducts }|--down--|| Products
Dishes ||----|{ Products

@enduml
